### ISSUE TITLE
[ELK] configure for syslog

### ISSUE THREAD

**Issue by zenxen3** [bitnami/vms#325]
### Describe your issue as much as you can

Hello,
I still use Bitnami ELK 6.4 as syslog, it works but I would like to install new one, Bitnami ELK 8.4.

elasticsearch.yml looks like this:
```
http:
  port: "9200"
path:
  data: /bitnami/elasticsearch/data
transport:
  port: "9300"
action:
  destructive_requires_name: "true"
network:
  host: 0.0.0.0
  publish_host: 192.168.11.243
  bind_host: 0.0.0.0
node:
  name: debian
discovery:
  type: single-node
xpack:
  security:
    enabled: "false"
  ml:
    enabled: "false"

```
logstash.conf

```
input {
  tcp {
    port => 1514
    type => syslog
  }

}

filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

output {
  elasticsearch { hosts => ["192.168.11.243:9200"] }
}
```
and it doesn't work. What and where should I configure to fix it?
