### ISSUE TITLE
[Prestashop Docker] ERROR ==> Could not connect to the database

### ISSUE THREAD

**Issue by BettyNutz** [bitnami/vms#471]
### Describe your issue as much as you can

Ive been using the bitnami [docker-compose.yml](https://github.com/bitnami/bitnami-docker-prestashop/blob/master/docker-compose.yml) to develop. This is configured to use persistence with my host. I then used commit and pushed up 2 images (mariadb & ps) to [docker hub](https://hub.docker.com/u/50pence). All good. Thing is - when i pull the images back down and spin up the two containers - either with:

```
sudo docker run -it -d --name mariadb-part --network="ps-1-7-persis_default" 50pence/maria-part:version1.0
sudo docker run -it -d --name mariadb-part -p 8080:80 --network="ps-1-7-persis_default" 50pence/maria-part:version1.0
```

or via a mod'd yml file, i cant get the PrestaShop container to finish the build?:

ERROR ==> Could not connect to the database

Is there something in a container that i need to change before i make the image?

```
version: '2'
services:
  mariadb:
    image: docker.io/50pence/maria-part:version1.0
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - MARIADB_ROOT_PASSWORD=bitnamiROOT
      - MARIADB_PASSWORD=bitnamiUSER
    volumes:
      - /home/betty/bitnami/mariadb:/bitnami/mariadb
  prestashop:
    image: docker.io/50pence/prestashop-part:version1.0
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=192.168.0.20
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_PASSWORD=bitnamiUSER
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - PRESTASHOP_FIRST_NAME=test
      - PRESTASHOP_LAST_NAME=test
      - PRESTASHOP_PASSWORD=password123 
      - PRESTASHOP_EMAIL=xjcqqsqsyskupjzxtp@tmmwj.net 
      - PHP_UPLOAD_MAX_FILESIZE=500M
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - /home/betty/bitnami/prestashop:/bitnami/prestashop
    depends_on:
      - mariadb
```
